### ISSUE TITLE
Can not create directory /run/user/0 - Permission denied

### ISSUE THREAD

**Issue by rockydares** [F33RNI/LlM-Api-Open#2]
```
2024-05-20 15:56:14 INFO     Loading cookies from /root/configs/copilot.json
2024-05-20 15:56:14 INFO     Loaded 17 cookies
2024-05-20 15:56:14 INFO     Adding chrome options
2024-05-20 15:56:14 INFO     Using user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-05-20 15:56:14 INFO     Initializing driver in headless mode
2024-05-20 15:56:14 INFO     Browser executable path: /snap/bin/chromium
2024-05-20 15:56:14 INFO     Running /snap/bin/chromium --version
mkdir: cannot create directory ‘/run/user/0’: Permission denied
2024-05-20 15:56:14 INFO     Detected major version: 124
2024-05-20 15:56:14 ERROR    ms_copilot initialization error
```

**Comment by rockydares** [comment]
This after providing google-chrome browser and driver path in ms_copilot config,

```
2024-05-20 16:06:56 INFO     Loading cookies from /root/configs/copilot.json
2024-05-20 16:06:56 INFO     Loaded 17 cookies
2024-05-20 16:06:56 INFO     Adding chrome options
2024-05-20 16:06:56 INFO     Using user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
2024-05-20 16:06:56 INFO     Initializing driver in headless mode
2024-05-20 16:06:56 INFO     Browser executable path: /usr/bin/google-chrome
2024-05-20 16:06:56 INFO     Running /usr/bin/google-chrome --version
2024-05-20 16:06:56 INFO     Detected major version: 125
2024-05-20 16:06:56 ERROR    ms_copilot initialization error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/lmao/module_wrapper.py", line 88, in _initialization_thread
    self._module_class.session_start(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lmao/ms_copilot/ms_copilot_api.py", line 356, in session_start
    raise e
  File "/usr/local/lib/python3.10/dist-packages/lmao/ms_copilot/ms_copilot_api.py", line 301, in session_start
    self.driver = undetected_chromedriver.Chrome(
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/patcher.py", line 136, in auto
    most_recent = max(files, key=lambda f: f.stat().st_mtime)
ValueError: max() arg is an empty sequence
```
